# -*- coding: utf-8 -*-
"""Copy of DDM_Wiggles_MT_AKCversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibhrqMrlUikSX6BJNzYks2Gw7YLvnBbt
"""

from one.api import ONE
#ONE.setup(base_url='https://openalyx.internationalbrainlab.org', silent=True)
#one = ONE(password='international')
from one.alf.io import AlfBunch

#@title Download files from Github
from pyddm import Sample
import pandas as pd
import numpy as np
import pickle
import requests
import io

# Links to github with wiggle and no-wiggle data of the supermouse (all trials concatenated)
#For the mice fitlered by having significant accuracy improvements with wiggles, use these links:
#urlWigg = "https://raw.githubusercontent.com/Marsataheri/DDM-for-wiggles/main/superMouse_WigglesConc.pkl"
#urlNW = "https://raw.githubusercontent.com/Marsataheri/DDM-for-wiggles/main/superMouse_NoWiggConc.pkl"
#For mice filtered by having an Organic Bias>5, use these links:
urlWigg = "https://raw.githubusercontent.com/Marsataheri/DDM-for-wiggles/main/superMouse_WigglesConc_OB.pkl"
urlNW = "https://raw.githubusercontent.com/Marsataheri/DDM-for-wiggles/main/superMouse_NoWiggConc_OB.pkl"

# Download the file content
FileWigg = requests.get(urlWigg)
FileNW = requests.get(urlNW)

# Save the content locally in Colab
with open("superMouse_WigglesConc.pkl", "wb") as f:
    f.write(FileWigg.content)
with open("superMouse_NoWiggConc.pkl", "wb") as f:
    f.write(FileNW.content)

# Load the AlfBunch from the pkl file
with open("superMouse_WigglesConc.pkl", "rb") as f:
    data_wigg = pickle.load(f)
with open("superMouse_NoWiggConc.pkl", "rb") as f:
    data_NW = pickle.load(f)

# Also choose which file you want to use as the data. For now, focusing
# on No-wiggle data:
# data = data_NW  # this is now handled by the condition selector cell below

#Verify it loaded
#print(f'File type: {type(data)}')   # should be dict
#print(f'Data keys: {data.keys()}')

#@title Select condition
# ============================================================
# CHANGE THESE TWO LINES TO SWITCH CONDITIONS:
BLOCK = 0.2        # Options: 0.2, 0.8, 'all'
USE_WIGGLE = False  # True for wiggle trials, False for no-wiggle
# ============================================================

# Function to get signed contrast for each trial:
def signed_contrast(trials):
    """Returns an array of signed contrasts in percent, where -ve values are on the left"""
    contrast = np.nan_to_num(np.c_[trials.contrastLeft, trials.contrastRight])
    return np.diff(contrast).flatten() * 100

# Select block
if BLOCK == 'all':
    block_WigglesConc = data_wigg
    block_NoWiggConc = data_NW
else:
    block_WigglesConc = AlfBunch({key: data_wigg[key][data_wigg['probabilityLeft'] == BLOCK] for key in data_wigg.keys()})
    block_NoWiggConc = AlfBunch({key: data_NW[key][data_NW['probabilityLeft'] == BLOCK] for key in data_NW.keys()})

# Select wiggle or no-wiggle
if USE_WIGGLE:
    block = block_WigglesConc
    condition_label = f"Wiggle | Block {BLOCK}"
else:
    block = block_NoWiggConc
    condition_label = f"No-wiggle | Block {BLOCK}"

# Compute key variables for downstream cells
respTimes = list(block.response_times - block.stimOn_times)
sc = signed_contrast(block) / 100
choices = (block['choice'] == -1).astype(int)

print(f"Running: {condition_label}")
print(f"Number of trials: {len(respTimes)}")

# Make dataframe Sample for DDM
rt_array = respTimes
choice_array = block['choice']
stim_array = signed_contrast(block)

df = pd.DataFrame({
    "rt": rt_array,
    "choice_raw": choice_array,
    "stim": stim_array
})

df["choice"] = (df["choice_raw"] == -1).astype(int)
df["stim"] = df["stim"] / 100
df["contrast_abs"] = np.abs(df["stim"])
df["side"] = np.sign(df["stim"])

sample = Sample.from_pandas_dataframe(
    df,
    rt_column_name="rt",
    choice_column_name="choice"
)

print(df)

"""# Fitting a DDM using PyDDM
To let the drift rate vary with the stim contrast, we must subclass Drift. Each subclass must contain a name (a short description of how drift varies), required parameters (a list of the parameters that must be passed when we initialize our subclass, i.e. parameters which are passed to the constructor), and required conditions (a list of conditions that must be present in any data when we fit data to the model). We then use this simplest case here (called "DriftScaled") to create a simple model (with no bias IC or collapsing bound).
"""

import warnings
import logging
import pyddm as ddm
import pyddm.plot
from pyddm import Model, Fittable, Fitted, Drift, Bound
from pyddm.functions import fit_adjust_model, display_model
from pyddm.models import NoiseConstant, BoundConstant, OverlayChain, OverlayNonDecision, OverlayPoissonMixture, LossRobustBIC
from pyddm.models import InitialCondition, ICPoint, ICPointSourceCenter
from pyddm.models import OverlayUniformMixture, OverlayPoissonMixture, OverlayNonDecision, OverlayChain
from pyddm.models.loss import LossRobustLikelihood
from pyddm.models.bound import BoundCollapsingExponential
from pyddm.models import OverlayNonDecisionUniform

warnings.filterwarnings("ignore")
logging.getLogger("pyddm").setLevel(logging.ERROR)

class DriftScaled(Drift):
    name = "Scaled drift"
    required_parameters = ["k", "alpha"]
    required_conditions = ["stim"]

    def get_drift(self, conditions, **kwargs):
        s = conditions["stim"]
        return self.k * np.sign(s) * (np.abs(s) ** self.alpha)

class ICPointFrac(InitialCondition):
    name = "Fractional bias"
    required_parameters = ["x0_frac"]

    def get_IC(self, x, dx, conditions):
        b = max(abs(x))
        if b == 0:
            b = dx
        x0 = self.x0_frac * b
        shift_i = int(round(x0 / dx)) + (len(x) - 1) // 2
        shift_i = int(np.clip(shift_i, 0, len(x) - 1))
        pdf = np.zeros(len(x))
        pdf[shift_i] = 1.0 / dx
        return pdf

class OverlayNonDecisionUniformLeftRight(OverlayNonDecisionUniform):
    name = "Left/right uniformly-distributed non-decision time"
    required_parameters = ["nondectime_left", "nondectime_right", "halfwidth"]
    required_conditions = ["stim"]

    def get_nondecision_time(self, conditions):
        if conditions["stim"] < 0:
            return self.nondectime_left
        return self.nondectime_right

class BoundCollapsingExponentialLeftRight(Bound):
    name = "Left/right collapsing exponential bound"
    required_parameters = ["B_left", "B_right", "tau"]
    required_conditions = ["stim"]

    def get_bound(self, t, conditions, **kwargs):
        if conditions["stim"] < 0:
            return self.B_left * np.exp(-self.tau * t)
        return self.B_right * np.exp(-self.tau * t)

model = Model(
    drift=DriftScaled(
        k=Fittable(minval=0, maxval=20),
        alpha=Fittable(minval=0.1, maxval=1.0)
    ),
    noise=NoiseConstant(noise=1),
    bound=BoundCollapsingExponentialLeftRight(
        B_left=Fittable(minval=0.1, maxval=0.8),
        B_right=Fittable(minval=0.1, maxval=0.8),
        tau=Fittable(minval=0.05, maxval=2.0)
    ),
    overlay=OverlayChain(overlays=[
        OverlayNonDecisionUniformLeftRight(
            nondectime_left=Fittable(minval=0.05, maxval=0.4),
            nondectime_right=Fittable(minval=0.05, maxval=0.4),
            halfwidth=Fittable(minval=0.0, maxval=0.2)
        ),
        OverlayPoissonMixture(pmixturecoef=0.05, rate=1)
    ]),
    IC=ICPointFrac(x0_frac=Fittable(minval=-0.99, maxval=0.99)),
    dx=0.02,
    dt=0.002,
    T_dur=1.5
)

df_small = df.sample(n=5000, random_state=43)
sample_small = Sample.from_pandas_dataframe(df_small, rt_column_name="rt", choice_column_name="choice")

fit_model = fit_adjust_model(sample=sample_small, model=model, lossfunction=LossRobustLikelihood, verbose=False)

print('Model fit completed.')

"""### **Print the resulting parameters and plot the psychometric and chronometric curves**"""

#Save parameters in a variable:
params = {
    name: (v.value if hasattr(v, "value") else v)
    for block in fit_model.parameters().values()
    for name, v in block.items()
}
print(params)

# Print model parameters in a nice table:
rows = []
for block, block_params in fit_model.parameters().items():
    for name, value in block_params.items():
        val = value.value if hasattr(value, "value") else value
        rows.append([block, name, val])

df_params = pd.DataFrame(rows, columns=["component", "parameter", "value"])
print(df_params)



# Extract and display fitted parameters
rows = []
for block_name, block_params in fit_model.parameters().items():
    for name, value in block_params.items():
        val = value.value if hasattr(value, "value") else value
        rows.append([block_name, name, val])

df_params = pd.DataFrame(rows, columns=["component", "parameter", "value"])
print(f"Condition: {condition_label}")
print("\n=== Fitted Parameters ===")
print(df_params.to_string(index=False))

# Data vs model comparison
stim_vals = np.sort(df["stim"].unique())
p_right_data, rt_data, p_right_model, rt_model = [], [], [], []

for c in stim_vals:
    subset = df[df["stim"] == c]
    p_right_data.append(subset["choice"].mean())
    rt_data.append(subset["rt"].mean())
    sol = fit_model.solve(conditions={"stim": c})
    p_right_model.append(sol.prob("upper_bound"))
    rt_model.append(sol.mean_rt())

print(f"\n=== Data vs Model ===")
print(f"{'Stim':>8} | {'P(right) data':>13} | {'P(right) model':>14} | {'RT data':>8} | {'RT model':>8}")
for i, c in enumerate(stim_vals):
    print(f"{c:>8.3f} | {p_right_data[i]:>13.3f} | {p_right_model[i]:>14.3f} | {rt_data[i]:>8.3f} | {rt_model[i]:>8.3f}")

print(f"\n=== RT Statistics ===")
print(f"Mean RT: {df['rt'].mean():.3f}s")
print(f"Median RT: {df['rt'].median():.3f}s")
print(f"RT < 0.5s: {(df['rt'] < 0.5).mean()*100:.1f}%")
print(f"RT < 1.0s: {(df['rt'] < 1.0).mean()*100:.1f}%")

# Run this while fit_model is still the WIGGLE fit
stim_smooth = np.linspace(-1, 1, 50)
p_right_smooth_wigg, rt_smooth_wigg = [], []
for c in stim_smooth:
    sol = fit_model.solve(conditions={"stim": c})
    p_right_smooth_wigg.append(sol.prob("upper_bound"))
    rt_smooth_wigg.append(sol.mean_rt())

print(f"=== {condition_label} smooth curve ===")
for i, c in enumerate(stim_smooth):
    print(f"{c:.4f}, {p_right_smooth_wigg[i]:.4f}, {rt_smooth_wigg[i]:.4f}")

print(f"=== {condition_label} error bars ===")
for c in stim_vals:
    subset = df[df["stim"] == c]
    n = len(subset)
    p = subset["choice"].mean()
    p_se = np.sqrt(p*(1-p)/n)
    print(f"{c:.4f}, {p:.4f}, {p_se:.4f}, {subset['rt'].mean():.4f}, {subset['rt'].sem():.4f}")

import matplotlib.pyplot as plt

# Psychometric and Chronometric curves:
stim_vals = np.sort(df["stim"].unique())

#Sample data:
p_right_data = []
rt_data = []
for c in stim_vals:
    subset = df[df["stim"] == c]
    p_right_data.append(subset["choice"].mean())  # assuming 1 = right
    rt_data.append(subset["rt"].mean())

#Model:
p_right_model = []
rt_model = []
if fit_model.required_conditions == ["stim"]:
    for c in stim_vals:
        sol = fit_model.solve(conditions={"stim": c})
        p_right_model.append(sol.prob("upper_bound"))
        ##Option 1; for more complex models gives assymetric results:
        #rt_model.append(sol.mean_decision_time()) #Already includes non-decision time so don't add params["nondectime"])
        ##Better option:
        rt_model.append(sol.mean_rt()) #Also already includes non-decision time!

#For more complex models (ignore for now):
elif fit_model.required_conditions==['side', 'contrast_abs']:
    for c in stim_vals:
        sol = fit_model.solve(conditions={
            "contrast_abs": abs(c),
            "side": np.sign(c) if c != 0 else 1
        })
        p_right_model.append(sol.prob("upper_bound"))
        ##Option 1; for more complex models gives assymetric results:
        #rt_model.append(sol.mean_decision_time()) #Already includes non-decision time so don't add params["nondectime"])
        ##Better option:
        rt_model.append(sol.mean_rt()) #Also already includes non-decision time!


###########################################
#Plot Psychometric curve:
plt.figure()
plt.plot(stim_vals, p_right_data, '-o', label="data")
plt.plot(stim_vals, p_right_model, '-o', label="model")
plt.xlabel("Signed contrast")
plt.ylabel("P(right)")
plt.legend()
plt.title("Psychometric curve")

###########################################
#Plot Chronometric curve:
plt.figure()
plt.plot(stim_vals, rt_data, '-o', label="data")
plt.plot(stim_vals, rt_model, '-o', label="model")
plt.xlabel("Signed contrast")
plt.ylabel("Mean RT (s)")
plt.legend()
plt.title("Chronometric curve")
plt.show()

###########################################

print(params)

"""### **The 3 GUIs below (especially the 3rd one) allow us to see results in more detail and play around with the model parameters**"""

pyddm.plot.model_gui_jupyter(model=model, sample=sample, plot=pyddm.plot.plot_psychometric('stim'))
#The sample data are the dots and the model is the curve

pyddm.plot.model_gui_jupyter(model=model, sample=sample, plot=pyddm.plot.plot_chronometric('stim'))
#The sample data are the dots and the model is the curve

pyddm.plot.model_gui_jupyter(model=model, sample=sample)
